config/routes.rb
Rails.application.routes.draw do
  # All routes in this scope will be prefixed with /locale if an available locale is set. See default_url_options in
  # application_controller.rb and http://guides.rubyonrails.org/i18n.html for more info on this approach.

  namespace :webhooks do
    resource :twilio, controller: :twilio, only: [] do
      post :status
    end
    resource :mailgun, controller: :mailgun, only: [] do
      post :status
      post :inbound
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'hello_worlds#show'

    devise_for :users,
               skip: [:registrations],
               controllers: {
                 confirmations: 'account/confirmations',
               },
               path: 'account'

    resource 'account', module: :account, only: [:show, :edit, :update] do
      resource 'setup', only: [:edit, :update], path_names: { edit: '' }
    end

    resource :privacy, only: [:show]
    resource :referral_information, only: [:show]

    namespace :admin do
      resources :organizations, only: :index
      resources :users, only: :index
      resources :aid_applications, only: :index
      resource :tasks do
        put :replace_payment_card
        put :undisburse_payment_card
        post :import_payment_cards
      end
      resources :messages, only: :index
    end

    resources :organizations, only: [] do
      scope module: :organizations do
        resource :dashboard, only: [:show]
        resources :assisters, except: [:destroy] do
          member do
            delete 'deactivate'
            post 'reactivate'
            post 'resend_confirmation_instructions'
            post 'send_password_reset_instructions'
          end
        end
        resource :export, only: [:show, :create]
        resources :aid_applications, only: [:show, :create, :destroy]
      end

      resources :aid_applications, only: [] do
        scope module: :aid_applications do
          resource :eligibility, only: [:edit, :update], path_names: { edit: '' }
          resource :applicant, only: [:edit, :update], path_names: { edit: '' }, defaults: { verify: false } do
            put :unpause
          end
          resource :confirmation, only: [:edit, :update], path_names: { edit: '' } do
            put 'update_contact_information'
          end
          resource :verification, controller: :applicants, only: [:edit, :update], path_names: { edit: '' }, defaults: { verify: true }
          resource :approval, only: [:edit], path_names: { edit: '' } do
            put :approve
            put :reject
            put :unapprove
            put :unreject
          end
          resource :duplicate, only: [:edit, :update], path_names: { edit: '' }
          resource :disbursement, only: [:edit, :update], path_names: { edit: '' }
          resource :finished, only: [:edit, :update], path_names: { edit: '' } do
            post 'reveal_activation_code'
          end
        end
      end
    end
  end

  # honeycrisp gem
  mount Cfa::Styleguide::Engine => "/cfa"
end

app/views/shared/_alerts.erb
<% if alert %>
  <div class="flash-container" id="dismiss-notice">
    <div class="flash flash--error">
      <p class="flash__message"><%= alert %></p>
      <a href="#dismiss-notice" class="flash__dismiss"><span class="icon icon-close"></span></a>
    </div>
  </div>
<% end %>

<% if notice %>
  <div class="flash-container" id="dismiss-notice">
    <div class="flash">
      <p class="flash__message"><%= notice %></p>
      <a href="#dismiss-notice" class="flash__dismiss"><span class="icon icon-close"></span></a>
    </div>
  </div>
<% end %>

app/views/shared/_demo_banner.erb
<div class="demo-banner">This site is for demonstration purposes only. Do not enter any personal information! If you need to submit an application go to <%= link_to 'ca-drai.org', 'https://www.ca-drai.org' %>.</div>

app/views/shared/_footer.erb
<div class="grid">
  <div class="main-footer__legal">
    <div class="grid__item width-two-thirds">
      <p><strong>DRAI Portal is a service delivered by Code for America on behalf of the people of California.</strong></p>
    </div>
  </div>

  <div class="grid__item width-one-fourth shift-one-twelfth">
    <div class="main-footer__cfa-logo">
      <a href="https://www.codeforamerica.org" class="illustration illustration--cfa-logo__dark">Code for America</a>
    </div>
  </div>
</div>

app/views/shared/_form_card.erb
<div class="grid__item width-two-thirds shift-one-sixth">
  <div class="form-card">
    <header class="form-card__header">
      <h1><%= title %></h1>
    </header>

    <%= form_for(form_resource, form_options.merge(builder: DafiFormBuilder)) do |f| %>
      <div class="form-card__content">
        <%= content.call(f) %>
      </div>

      <div class="form-card__footer">
        <%= footer.call(f) %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.erb
<div class="<%= local_assigns[:header_class] %>">
  <header class="main-header">
    <div class="toolbar">
      <div class="toolbar__left">
        <div class="main-header__title">
          <%= link_to "DRAI Portal", root_path, class: "main-header__no-logo" %>
        </div>
      </div>
      <div class="toolbar__right">
        <% if current_user.present? %>
          <% if current_user.organization.present? %>
            <%= link_to 'Dashboard', organization_dashboard_path(current_user.organization), class: 'toolbar__item text--small' %>
          <% else %>
            <%= link_to 'Admin', admin_organizations_path, class: 'toolbar__item text--small' %>
          <% end %>
          <%= link_to 'Account', account_path, class: 'toolbar__item text--small' %>
          <%= link_to "Sign out", destroy_user_session_path, class: "toolbar__item text--small" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "toolbar__item text--small" %>
        <% end %>
      </div>
    </div>
  </header>
</div>

app/views/shared/_searchbar.erb
<%= form_with method: "get", local: true do |f| %>
  <div class="toolbar">
    <div class="toolbar__left">
      <div class="searchbar form-width--searchbar">
        <%= text_field_tag "q",
                           params[:q],
                           placeholder: placeholder,
                           class: "searchbar__input",
                           autofocus: true %>

        <label class="searchbar__button">
          <span class="icon icon-arrow_forward"></span>
          <button type="submit">
            <span class="sr-only">Search</span>
          </button>
        </label>
      </div>
    </div>

    <div class="toolbar__right">
      <div class="form-group">
        <label class="sr-only" for="status">
          <p class="form-question">Filter</p>
        </label>
        <div class="select">
          <% statuses = [
              ['All', nil],
              ['Submitted', :submitted],
              ['Verified', :verified],
              ['Approved', :approved],
              ['Disbursed', :disbursed],
              ['Paused', :paused],
              ['Waitlisted', :waitlisted],
              ['Rejected', :rejected],
          ] %>
          <%= f.select :status, statuses, { selected: params[:status] }, { onchange: 'this.form.submit();', class: ['select__element'] } %>
        </div>

        <label class="sr-only" for="order">
          <p class="form-question">Order</p>
        </label>
        <div class="select">
          <% statuses = [
              ['Newest', :desc],
              ['Oldest', :asc],
          ] %>
          <%= f.select :order, statuses, { selected: params[:order] }, { onchange: 'this.form.submit();', class: ['select__element'] } %>
        </div>
      </div>
    </div>
  </div>
<% end %>