config/routes.rb
Rails.application.routes.draw do
  # All routes in this scope will be prefixed with /locale if an available locale is set. See default_url_options in
  # application_controller.rb and http://guides.rubyonrails.org/i18n.html for more info on this approach.

  namespace :webhooks do
    resource :twilio, controller: :twilio, only: [] do
      post :status
    end
    resource :mailgun, controller: :mailgun, only: [] do
      post :status
      post :inbound
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'hello_worlds#show'

    devise_for :users,
               skip: [:registrations],
               controllers: {
                 confirmations: 'account/confirmations',
               },
               path: 'account'

    resource 'account', module: :account, only: [:show, :edit, :update] do
      resource 'setup', only: [:edit, :update], path_names: { edit: '' }
    end

    resource :privacy, only: [:show]
    resource :referral_information, only: [:show]

    namespace :admin do
      resources :organizations, only: :index
      resources :users, only: :index
      resources :aid_applications, only: :index
      resource :tasks do
        put :replace_payment_card
        put :undisburse_payment_card
        post :import_payment_cards
      end
      resources :messages, only: :index
    end

    resources :organizations, only: [] do
      scope module: :organizations do
        resource :dashboard, only: [:show]
        resources :assisters, except: [:destroy] do
          member do
            delete 'deactivate'
            post 'reactivate'
            post 'resend_confirmation_instructions'
            post 'send_password_reset_instructions'
          end
        end
        resource :export, only: [:show, :create]
        resources :aid_applications, only: [:show, :create, :destroy]
      end

      resources :aid_applications, only: [] do
        scope module: :aid_applications do
          resource :eligibility, only: [:edit, :update], path_names: { edit: '' }
          resource :applicant, only: [:edit, :update], path_names: { edit: '' }, defaults: { verify: false } do
            put :unpause
          end
          resource :confirmation, only: [:edit, :update], path_names: { edit: '' } do
            put 'update_contact_information'
          end
          resource :verification, controller: :applicants, only: [:edit, :update], path_names: { edit: '' }, defaults: { verify: true }
          resource :approval, only: [:edit], path_names: { edit: '' } do
            put :approve
            put :reject
            put :unapprove
            put :unreject
          end
          resource :duplicate, only: [:edit, :update], path_names: { edit: '' }
          resource :disbursement, only: [:edit, :update], path_names: { edit: '' }
          resource :finished, only: [:edit, :update], path_names: { edit: '' } do
            post 'reveal_activation_code'
          end
        end
      end
    end
  end

  # honeycrisp gem
  mount Cfa::Styleguide::Engine => "/cfa"
end

app/controllers/organizations/assisters_controller.rb
module Organizations
  class AssistersController < ApplicationController
    before_action :authenticate_supervisor!
    before_action :prevent_self_action, only: [:deactivate, :reactivate, :resend_confirmation_instructions, :send_password_reset_instructions]

    def index
      users_query = current_organization.users.includes(:organization).order(id: :desc)

      @users = users_query.activated
      @deactivated_users = users_query.deactivated
    end

    def new
      @user = User.new(organization: current_organization)
    end

    def create
      @user = User.new(user_params.merge(
        organization: current_organization,
        inviter: current_user
      ))
      @user.save

      respond_with @user, location: -> { organization_assisters_path(current_organization) }, notice: "Sent invite to #{@user.email}"
    end

    def edit
      @user = user_from_params
    end

    def update
      @user = user_from_params
      @user.update(user_params)
      respond_with @user, location: -> { organization_assisters_path(current_organization) }
    end

    def deactivate
      @user = user_from_params
      @user.update(deactivated_at: Time.current) if @user.deactivated_at.nil?

      respond_with @user, notice: "Deactivated #{@user.name}", location: -> { organization_assisters_path(current_organization) }
    end

    def reactivate
      @user = user_from_params
      @user.update(deactivated_at: nil) if @user.deactivated_at.present?

      respond_with @user, notice: "Reactivated #{@user.name}", location: -> { organization_assisters_path(current_organization) }
    end

    def resend_confirmation_instructions
      @user = user_from_params
      if @user.confirmed_at.blank?
        @user.send_confirmation_instructions
      end
      respond_with @user, notice: "Resent confirmation for #{@user.name}", location: -> { organization_assisters_path(current_organization) }
    end

    def send_password_reset_instructions
      @user = user_from_params
      if @user.confirmed_at.present?
        @user.send_reset_password_instructions
      end
      respond_with @user, notice: "Sent password reset for #{@user.name}", location: -> { organization_assisters_path(current_organization) }
    end

    private

    def prevent_self_action
      redirect_back(fallback_location: root_path) if user_from_params == current_user
    end

    def user_params
      params.require(:user).permit(:name, :email, :supervisor)
    end

    def user_from_params
      @_user_from_params ||= current_organization.users.find(params[:id])
    end
  end
end

app/views/assisters/_form.erb
<% content = capture_form do |f| %>
  <%= f.cfa_input_field :name, "Name", classes: ["form-width--long"] %>
  <%= f.cfa_input_field :email, "Email Address", classes: ["form-width--long"] %>

  <% unless current_organization %>
    <%= f.cfa_select(:organization_id, "Organization", Organization.all.order(name: :asc).map { |org| [org.name, org.id] }, prompt: "Select Organization") %>
  <% end %>

  <%= f.cfa_select :supervisor, "Role and Permissions", [['Assister', false], ['Supervisor', true]], help_text: "Supervisors have additional permissions to manage assisters and application information." %>
<% end %>

<% footer = capture_form do |f| %>
  <%= f.cfa_button button_label %>
  <%= link_to "Cancel", current_organization ? organization_assisters_path(current_organization) : assisters_path %>
<% end %>

<%= render 'shared/form_card',
           form_resource: user,
           form_options: { url: { action: user.persisted? ? :update : :create } },
           title: title,
           content: content,
           footer: footer
%>

app/views/assisters/edit.html.erb
<%= render 'form', user: @user, title: "Edit assister", button_label: 'Edit assister' %>

<div class="grid__item width-two-thirds shift-one-sixth">
  <br>
  <h3>Changelog</h3>
  <ul class="list--bulleted">
    <%
      showable_changes = [:name, :email, :supervisor, :deactivated_at]
      versions = @user.versions.includes(:item).reorder(created_at: :desc).select { |v| v.changeset.any? { |(field, _values)| field.to_sym.in? showable_changes} }
      actors_by_id = User.where(id: versions.pluck(:whodunnit).uniq).index_by(&:id)
    %>

    <% versions.each do |version| %>
      <li>
        <strong>
          <% if actor = actors_by_id[version.whodunnit.to_i] %>
            <%= actor.name %>
          <% else %>
            Automated Process
          <% end %>
        </strong>
        <% if version.event == 'create' %>
          sent an invite
        <% else %>
          <%= version.changeset.reject { |c| c == 'updated_at' }.map do |(field, (original_value, new_value))| %>
            <% capture do %>
              <% if field == 'deactivated_at' %>
                <% if original_value.present? && new_value.blank? %>
                  reactivated account
                <% else %>
                  deactivated account
                <% end %>
              <% else %>
                changed
                <strong><%= field %></strong>
                from <strong><%= original_value %></strong>
                to <strong><%= new_value %></strong>
              <% end %>
            <% end %>
          <% end.to_sentence.html_safe %>
        <% end %>
        about <strong title="<%= version.created_at %>"><%= time_ago_in_words(version.created_at) %> ago</strong>.
      </li>
    <% end %>
  </ul>
</div>